#!/usr/bin/env -S deno run -A
// vim: set ft=typescript
//MISE hide=true
//USAGE arg "<VERSION>" env="BUILD_VERSION"
//USAGE arg "<PLATFORM>" env="BUILD_PLATFORM"
//USAGE arg "<SRC>"

import $ from '@david/dax'
import { parse as pathParse } from 'node:path'

const src = Deno.env.get('usage_src')!
const binName = pathParse(src).name
const dst = $.path('build').join(binName)

// "deno compile" cannot pass source file from STDIN
// https://github.com/denoland/deno/issues/26593#issuecomment-2537769762
const bundledSrc = await Deno.makeTempFile({ prefix: `${binName}-`, suffix: '.bundle.js' })
await $`deno bundle --minify --platform deno --output ${bundledSrc} ${src}`

// Inject CLI version via "deno compile" rest args
// https://github.com/denoland/deno/issues/9152#issuecomment-773522311
const version = Deno.env.get('usage_version')!
const platform = Deno.env.get('usage_platform')!
await $`deno compile --allow-all --target ${platform} --output ${dst} ${bundledSrc} ${version}`
